let data = [
    {
        title : 'Cristo Redentor', 
        location : 'Brasil', 
        googleMapsUrl : 'https://www.google.com/maps/place/Cristo+Redentor/@-22.951911,-43.2126759,17z/data=!3m1!4b1!4m5!3m4!1s0x997fd5984aa13f:0x9dc984d7019502de!8m2!3d-22.951916!4d-43.2104872',
        startDate : '01 Dez, 2022',
        endDate : '08 Dez, 2022',
        description : 'Das 7 maravilhas do mundo moderno, o Cristo Redentor é a mais nova e a mais perto para nós brasileiros visitarmos. De braços abertos sobre a Guanabara, no Rio de Janeiro, a obra teve a sua construção iniciada em 1926 e foi inaugurada em 12 de outubro de 1931. A estátua está localizada no topo do Morro do Corcovado a 709 metros sobre o nível do mar. O Cristo Redentor possui 30 metros de altura e está sobre uma base de 8 metros. Seus braços estendidos alcançam 28 metros. O Cristo Redentor é um dos Pontos turísticos do Rio de Janeiro mais visitados! Você pode ir por sua conta ou fazer um tour no Corcovado.',
        imageUrl : 'https://www.melhoresdestinos.com.br/wp-content/uploads/2017/07/visao-aerea-cristo-redentor-820x463.jpg',
    },
    {
        title : 'Chichén Itzá',
        location : 'México',
        googleMapsUrl : 'https://www.google.com/maps/search/Chich%C3%A9n+Itz%C3%A1/@20.6809818,-88.5728543,16z/data=!3m1!4b1',
        startDate : '08 Dez, 2022',
        endDate : '14 Dez, 2022',
        description : 'Chichén Itzá foi uma das principais cidades do povo maia e é um dos sítios arqueológicos mais visitados no México. Cerca de 1,5 milhão de turistas visitam as ruínas a cada ano.        A cidade de Chichén Itzá foi construída entre séculos IX e XII e abandonada em 670 d.C. O ponto alto da visita é , sem dúvidas, El Castillo, também conhecido como a Pirâmide de Kukulcán. Ele é o templo principal, onde duas vezes por ano sombras reproduzem a imagem de Kukulcán, a serpente plumada. Sua construção é magnífica e realmente impressionante.',
        imageUrl : 'https://www.melhoresdestinos.com.br/wp-content/uploads/2020/05/chichen-itza-mexico-cancun.jpg',
    },
    {
        title : 'Coliseu ',
        location : 'Italia',
        googleMapsUrl : 'https://www.google.com/maps/place/Coliseu/@41.8902142,12.4900422,17z/data=!3m1!4b1!4m5!3m4!1s0x132f61b6532013ad:0x28f1c82e908503c4!8m2!3d41.8902102!4d12.4922309',
        startDate : '08 Dez, 2022',
        endDate : '14 Dez, 2022',
        description : 'Um dos monumentos mais famosos do mundo, o Coliseu atrai milhões de turistas todos os anos. O suntuoso símbolo do Império Romano, cuja construção foi iniciada pelo Imperador Vespasiano em 72 d.C., foi palco de combate entre gladiadores e batalhas com animais, performances que costumavam ser assistidas por um ávido público de até 73 mil pessoas.',
        imageUrl : 'https://www.melhoresdestinos.com.br/wp-content/uploads/2017/09/roma-italia_1067-820x547.jpg',
    },
    {
        title : 'Grande Muralha da China',
        location : 'China',
        googleMapsUrl : '',
        startDate : '08 Jan, 2023',
        endDate : '14 Jan, 2022',
        description : 'A construção se iniciou no século 7 a.C. e continuou por mais de 2000 mil anos. Ao longo do tempo ela ganhou novos muros, quartéis e torres de observação. A  Grande Muralha da China foi construída com propósito de proteger os estados e impérios chineses de invasões inimigas principalmente dos mongóis.        Apesar dos seus 21.196 km de extensão, o monumento possui diversas partes abertas à visitação que podem ser facilmente acessadas a partir de Pequim por transporte público, de trem ou excursões em português.',
        imageUrl : 'https://www.melhoresdestinos.com.br/wp-content/uploads/2017/12/muralha-china-820x545.jpg',
    },
    {
        title : 'Wadi Musa',
        location : 'Jordânia',
        googleMapsUrl : 'https://www.google.com/maps/place/Wadi+Musa,+Jord%C3%A2nia/@30.3192019,35.4788447,15.5z/data=!4m5!3m4!1s0x15016930021ab6b1:0xe43a697bc3a3e0b9!8m2!3d30.3216354!4d35.4801251',
        startDate : '08 Jan, 2023',
        endDate : '14 Jan, 2022',
        description : 'A paisagem desértica da Jordânia é recortada por montanhas imponentes e de tom avermelhado, esculpidas pelo vento ao longo de milhares de anos. No meio destas montanhas, surgiu Petra. Estabelecida possivelmente já em 312 a.C. como a capital dos árabes nabateus,o local foi importante e se desenvolveu ao longo da Rota da Seda. No auge, Petra abrigou cerca de 30 mil pessoas.',
        imageUrl : 'https://www.melhoresdestinos.com.br/wp-content/uploads/2018/11/jordania-capa2019-1-820x430.jpg',
    },
    {
        title : 'Machu Picchu',
        location : 'Peru',
        googleMapsUrl : 'https://www.google.com/maps/place/Machu+Picchu/@-13.163136,-72.5471516,17z/data=!3m1!4b1!4m5!3m4!1s0x916d9a5f89555555:0x3a10370ea4a01a27!8m2!3d-13.1631412!4d-72.5449629',
        startDate : '02 Jan, 2023',
        endDate : '24 Jan, 2022',
        description : 'A cidade perdida dos Incas exala energia e permite aos visitantes desvendar um pouquinho de um povo que guardava conhecimento muito avançado, especialmente para a época. O sítio arqueológico está 2.450 metros acima do nível do mar e foi povoado entre os anos de 1450 a 1540. As famílias que lá viviam cultivavam, principalmente, milho e batata e deixaram a cidade antes da chegada dos espanhóis. A melhor forma para visitar a cidade é chegar a Águas Calientes, na base de Machu Picchu, de trem saindo de Cusco, no Peru. Você pode visitar as ruínas por conta própria ou se preferir um tour guiado por Machu Picchu.',
        imageUrl : 'https://www.melhoresdestinos.com.br/wp-content/uploads/2019/03/peru-cusco-machu-picchu1-820x546.jpg',
    },
    {
        title : 'Taj Mahal',
        location : 'India',
        googleMapsUrl : 'https://www.google.com/maps/place/Taj+Mahal/@27.1751496,78.0399535,17z/data=!3m1!4b1!4m5!3m4!1s0x39747121d702ff6d:0xdd2ae4803f767dde!8m2!3d27.1751448!4d78.0421422',
        startDate : '09 Jan, 2023',
        endDate : '30 Jan, 2022',
        description : 'O Taj Mahal é a principal atração turística da Índia e um dos monumentos mais importantes do mundo. Localizado na cidade de Agra, foi eleito uma das Sete  Maravilhas do mundo moderno e atrai visitantes o ano todo.',
        imageUrl : 'https://www.melhoresdestinos.com.br/wp-content/uploads/2016/04/india-taj-mahal-1009262_1280.jpg',
    }
]
export default data
